<a href="https://colab.research.google.com/github/mori8/NLP-Pytorch-practice/blob/main/Chapter_1_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

## 1. 2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.

In [16]:
x = torch.rand(2, 3)
print(x)

x = x.unsqueeze(0)
print(x)

tensor([[0.1979, 0.9915, 0.5427],
        [0.6097, 0.0198, 0.6830]])
tensor([[[0.1979, 0.9915, 0.5427],
         [0.6097, 0.0198, 0.6830]]])


## 2. 이전 텐서에 추가한 차원을 삭제하세요.

In [17]:
x = x.squeeze()
print(x)

tensor([[0.1979, 0.9915, 0.5427],
        [0.6097, 0.0198, 0.6830]])


## 3. 범위가 [3, 7)이고 크기가 5x3인 랜덤한 텐서를 만드세요.

In [32]:
# x = torch.randint(3, 7, (5, 3))
y = 3 + torch.rand(5, 3) * (7 - 3)
print(y)

tensor([[4.0345, 3.0877, 3.1114],
        [6.1356, 4.2274, 3.1316],
        [5.0390, 6.8525, 5.6938],
        [6.5724, 6.6052, 4.3417],
        [3.7179, 6.8275, 3.1195]])


## 4. 정규 분포(평균 = 0, 표준편차 = 1)를 사용해 텐서를 만드세요.

In [21]:
x = torch.randn(9, 6)
print(x)

tensor([[-0.3387,  0.8933, -0.4763,  0.5968,  0.3245, -1.2078],
        [-0.8244,  2.1357,  1.3658, -0.0092, -0.4189, -0.1693],
        [-1.0855,  0.0241, -1.6467, -1.1751, -0.6032, -1.2480],
        [-0.0462,  0.4032, -0.0227, -1.3231,  0.6151,  0.4570],
        [-1.1470,  0.6683,  0.5349,  1.8625, -1.6285,  1.7796],
        [ 0.4911,  1.1044, -0.0661,  0.7507,  1.2765, -1.0844],
        [ 1.4902, -1.5565,  0.8874, -0.4624,  0.3194, -0.1501],
        [-0.4221,  0.2501, -0.8666, -1.3334, -0.8982,  0.4160],
        [ 1.6878, -0.0999, -1.2372,  2.6932,  0.2965,  1.5791]])


## 5. 텐서 torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스를 추출하세요.

In [22]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

## 6. 크기가 (3, 1)인 랜덤한 텐서를 만들고 네 벌을 복사해 넣으세요.

In [34]:
x = torch.rand(3, 1)
# x = torch.cat([x, x, x, x], 0)
x = x.expand(3, 4)
print(x)

tensor([[0.4948, 0.4948, 0.4948, 0.4948],
        [0.1138, 0.1138, 0.1138, 0.1138],
        [0.8670, 0.8670, 0.8670, 0.8670]])


## 7. 3차원 행렬 두 개의 배치 행렬 곱셈을 계산하세요.

In [29]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)

x = torch.bmm(a, b)
print(x)

tensor([[[2.2838, 1.5205, 2.0232, 1.2393],
         [1.8896, 1.4858, 2.0987, 1.2838],
         [2.2246, 1.7107, 2.6902, 1.4299],
         [1.8593, 1.3022, 2.1293, 1.0192]],

        [[1.1781, 0.9434, 0.8682, 1.1143],
         [1.3768, 0.8465, 1.5260, 1.7951],
         [1.2674, 1.5968, 1.1291, 1.4617],
         [0.5751, 0.4179, 0.2971, 0.4026]],

        [[1.0872, 2.5749, 1.1058, 2.4070],
         [0.7925, 1.8040, 0.9332, 1.9648],
         [1.1747, 2.7730, 0.9689, 1.9601],
         [0.8554, 1.9509, 0.9273, 1.3932]]])


## 8. 3차원 행렬과 2차원 행렬의 배치 행렬 곱셈을 계산하세요.

In [31]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)

x = torch.matmul(a, b)
# x = torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))
print(x)

tensor([[[1.6449, 2.2169, 2.5324, 1.8259],
         [0.6725, 1.3796, 1.5970, 0.9099],
         [1.6986, 2.2906, 2.6241, 1.9438],
         [1.1414, 1.2640, 1.4569, 1.1245]],

        [[0.7002, 1.5854, 1.7030, 1.0699],
         [1.4542, 1.9033, 2.1290, 1.6473],
         [1.4262, 1.5596, 1.9046, 1.4895],
         [1.3642, 2.0726, 2.4510, 1.3321]],

        [[1.4490, 1.8794, 2.2670, 1.3122],
         [1.5121, 2.0012, 2.3813, 1.6121],
         [0.7722, 1.8420, 2.0167, 1.2054],
         [1.3149, 1.8814, 2.2498, 1.1207]]])
